version: "3.8"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "4000:3000"
    depends_on:
      - prometheus

  web-metrics-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-metrics-service
    ports:
      - "3002:3002"

volumes:
  prometheus-data:
  grafana-storage:
